site_name: Beets Documentation
theme:
  # logo: assets/images/beets_symbol_wht_250x232.png
  logo: assets/images/beets_wht_250x744.png
  custom_dir: docs/overrides/
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: orange
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: amber
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.suggest
    - content.code.copy
    - navigation.top
extra_css:
  - assets/stylesheets/custom.css
nav:
  - Home:
    - Welcome: index.md
    - Beets CSS: beets-css/index.md
    - Beets Layout: beets-layout/index.md
    - Beets PHP: beets-php/index.md
  - Beets CSS:
    - About: beets-css/index.md
    - Getting started: beets-css/getting-started.md
    - Download: https://github.com/jonasbirkelof/beets-css
    - Forms:
      - Checks and radios: beets-css/forms/checks-and-radios.md
    - Components:
      - Breadcrumb: beets-css/components/breadcrumb.md
      - Buttons: beets-css/components/buttons.md
      - Callout: beets-css/components/callout.md
      - Card: beets-css/components/card.md
      - Dropdowns: beets-css/components/dropdowns.md
      - Modal: beets-css/components/modal.md
    - Utilities:
      - Colors: beets-css/utilities/colors.md
      - Cursor: beets-css/utilities/cursor.md
      - Spacing: beets-css/utilities/spacing.md
  - Beets Layout:
    - About: beets-layout/index.md
    - Download: beets-layout/download.md
    - Install: beets-layout/install.md
    - Sections:
      - Overview: beets-layout/section/overview.md
      - Logo: beets-layout/section/logo.md
      - Sidebar: beets-layout/section/sidebar.md
      - Main: beets-layout/section/main.md
      - Header: beets-layout/section/header.md
      - Body: beets-layout/section/body.md
      - Footer: beets-layout/section/footer.md
  - Beets PHP:
    - Om Beets PHP: beets-php/index.md
    - Content:
      - CSRF Protection: beets-php/csrf-protection.md
      - Database workflow: beets-php/database.md
      - Feedback messages: beets-php/feedback-messages.md
      - Form methods: beets-php/form-methods.md
      - Form validation: beets-php/form-validation.md
      - Functions:
        - App functions: beets-php/app-functions.md
        - Custom functions: beets-php/custom-functions.md
      - Redirecting: beets-php/redirecting.md
      - Sessions: beets-php/sessions.md
      - User authentication: beets-php/user-authentication.md
    - Configuration:
      - .env: beets-php/configuration/env.md
      - app.php: beets-php/configuration/app.md
      - data.php: beets-php/configuration/data.md
      - dotenv.php: beets-php/configuration/dotenv.md
plugins:
  - search
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde